#cloud-config
users:
  - name: andre
    groups: [docker, wheel]
    ssh_import_id:
      - gh:mniak
    hashed_passwd: $y$j9T$BJMsrsz7rX2YfKLloiviZ/$tRGGory9VM7Qu/xg0fY/PjKZ8lzr9tD/YYfeAgG3pk7
ssh_pwauth: false